"""add strategy metrics columns

Revision ID: 058bf947c029
Revises: 156bfa76279c
Create Date: 2026-03-14 19:46:28.107661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058bf947c029'
down_revision: Union[str, Sequence[str], None] = '156bfa76279c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('trade_count', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('max_drawdown', sa.Float(), nullable=True))
    op.add_column('strategies', sa.Column('sharpe_ratio', sa.Float(), nullable=True))
    op.add_column('strategies', sa.Column('win_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'win_rate')
    op.drop_column('strategies', 'sharpe_ratio')
    op.drop_column('strategies', 'max_drawdown')
    op.drop_column('strategies', 'trade_count')
    # ### end Alembic commands ###
