"""freqtrade integration: add user.is_admin, signal extension fields, backtest task fields

Revision ID: 156bfa76279c
Revises: 005
Create Date: 2026-03-14 19:02:59.159672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156bfa76279c'
down_revision: Union[str, Sequence[str], None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_tasks', sa.Column('timerange', sa.String(length=64), nullable=True))
    op.add_column('backtest_tasks', sa.Column('result_json', sa.JSON(), nullable=True))
    op.add_column('trading_signals', sa.Column('signal_source', sa.String(length=32), server_default='realtime', nullable=False))
    op.add_column('trading_signals', sa.Column('entry_price', sa.Float(), nullable=True))
    op.add_column('trading_signals', sa.Column('stop_loss', sa.Float(), nullable=True))
    op.add_column('trading_signals', sa.Column('take_profit', sa.Float(), nullable=True))
    op.add_column('trading_signals', sa.Column('indicator_values', sa.JSON(), nullable=True))
    op.add_column('trading_signals', sa.Column('timeframe', sa.String(length=16), nullable=True))
    op.add_column('trading_signals', sa.Column('signal_strength', sa.Float(), nullable=True))
    op.add_column('trading_signals', sa.Column('volume', sa.Float(), nullable=True))
    op.add_column('trading_signals', sa.Column('volatility', sa.Float(), nullable=True))
    op.drop_index(op.f('idx_signal_strategy_at'), table_name='trading_signals')
    op.create_index('idx_signal_strategy_at', 'trading_signals', ['strategy_id', 'signal_at'], unique=False)
    op.create_index('idx_signal_strategy_source', 'trading_signals', ['strategy_id', 'signal_source'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_admin')
    op.drop_index('idx_signal_strategy_source', table_name='trading_signals')
    op.drop_index('idx_signal_strategy_at', table_name='trading_signals')
    op.create_index(op.f('idx_signal_strategy_at'), 'trading_signals', ['strategy_id', sa.literal_column('signal_at DESC')], unique=False)
    op.drop_column('trading_signals', 'volatility')
    op.drop_column('trading_signals', 'volume')
    op.drop_column('trading_signals', 'signal_strength')
    op.drop_column('trading_signals', 'timeframe')
    op.drop_column('trading_signals', 'indicator_values')
    op.drop_column('trading_signals', 'take_profit')
    op.drop_column('trading_signals', 'stop_loss')
    op.drop_column('trading_signals', 'entry_price')
    op.drop_column('trading_signals', 'signal_source')
    op.drop_column('backtest_tasks', 'result_json')
    op.drop_column('backtest_tasks', 'timerange')
    # ### end Alembic commands ###
